on:
  push:
    paths:
      - '**/*.cs'
      - '**/*.csproj'
      - '**/*.sln'
  pull_request:
    paths:
      - '**/*.cs'
      - '**/*.csproj'
      - '**/*.sln'

name: Continuous Integration

jobs:
  inspect-code:
     name: CQ Check
     runs-on: ubuntu-latest
     steps:
        - name: Checkout
          uses: actions/checkout@v2

        # FIXME: Tools won't run in .NET 5.0 unless you install 3.1.x. 
        # Looks like we won't change this until 6.0 LTS releases on 11/2021.
        - name: Install .NET 5.0.x
          uses: actions/setup-dotnet@v1
          with:
             dotnet-version: '5.0.x'

        - name: Install .NET 3.1.x LTS
          uses: actions/setup-dotnet@v1
          with:
             dotnet-version: '3.1.x'
  
        - name: Restore Tools
          run: dotnet tool restore
        
        - name: Restore Packages
          run: dotnet restore
    
        - name: Inspect
          run: |
            dotnet jb inspectcode $(pwd)/osu-framework.Desktop.slnf --output=inspectcodereport.xml --cachesDir=$(pwd)/inspectcode --verbosity=WARN
            dotnet nvika parsereport $(pwd)/inspectcodereport.xml  --treatwarningsaserrors 

        
           